# Generated by Django 3.2.9 on 2021-11-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_auto_20211120_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaner', models.TextField(default="loaner's name")),
                ('on_loan', models.BooleanField(default=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.JSONField(default='owner'),
        ),
        migrations.DeleteModel(
            name='GameInfo',
        ),
        migrations.AddField(
            model_name='loan',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgames.game'),
        ),
    ]
