# Generated by Django 3.2.9 on 2021-11-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_auto_20211120_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='onLoan',
            new_name='on_loan',
        ),
    ]
