# Generated by Django 3.2.9 on 2021-12-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_auto_20211125_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loaner',
            field=models.TextField(default='write your name'),
        ),
    ]
