# Generated by Django 3.2.9 on 2021-12-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_alter_loan_loaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Describe your game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.CharField(default='Owner', max_length=250),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaner',
            field=models.CharField(default='Write your name', max_length=50),
        ),
    ]
